/* Run: node --test tests/dns.test.cjs */
const { test }=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs'); const vm=require('node:vm'); const context=vm.createContext({console,window:{crypto:require('node:crypto').webcrypto}});
for(const file of ['scenario_factory.js','challenge_runner.js','expert_attempt_runner.js','engine/ipv4_address.js','engine/dns_model.js','engine/dns_generator.js']) vm.runInContext(fs.readFileSync(`static/js/${file}`,'utf8'),context,{filename:file});
const model=vm.runInContext('DnsModel',context),generator=vm.runInContext('DnsGenerator',context),factory=vm.runInContext('ScenarioFactory',context),Runner=vm.runInContext('ExpertAttemptRunner',context),Challenge=vm.runInContext('ChallengeRunner',context); const lesson=JSON.parse(fs.readFileSync('lessons/computer_networks/dns.json','utf8')); const plain=v=>JSON.parse(JSON.stringify(v));
const answer=p=>{const r=model.resolve(p);return{cacheResult:r.cacheResult,resolvedIp:r.resolvedIp,destinationServerId:r.destinationServerId,sequence:r.sequence};};
test('cache miss queries DNS, resolves, and updates cache',()=>{const r=model.resolve(lesson.visualization.problems[0]);assert.equal(r.cacheResult,'miss');assert.deepEqual(plain(r.sequence),['CHECK_CACHE','CACHE_MISS','DNS_QUERY','DNS_RESPONSE','CACHE_UPDATE','RESOLVED']);assert.equal(r.cacheAfter['learn.example'],'203.0.113.20');});
test('cache hit avoids a new DNS query',()=>{const r=model.resolve(lesson.visualization.problems[1]);assert.equal(r.cacheResult,'hit');assert.deepEqual(plain(r.sequence),['CHECK_CACHE','CACHE_HIT','RESOLVED']);});
test('missing domain produces bounded NOT_FOUND consequence',()=>{const p={records:lesson.visualization.problems[0].records,cache:{},query:{domain:'missing.example'}};const r=model.resolve(p);assert.equal(r.found,false);assert.equal(r.resolvedIp,'NOT_FOUND');assert.equal(r.destinationServerId,'NONE');});
test('DNS result explains resolution without claiming to fetch content',()=>{const r=model.resolve(lesson.visualization.problems[0]);assert.match(r.explanation,/did not fetch|later HTTP/i);});
test('replay reveals every event once and in order',()=>{const replay=model.createReplay(lesson.visualization.problems[0]),events=[];while(events.length<replay.getLength()){const step=replay.next();events.push(step.event);}assert.deepEqual(events,plain(replay.getResult().sequence));assert.equal(replay.next().event,null);});
test('field assessment rejects wrong order and partial answers',()=>{const p=lesson.visualization.problems[0],correct=answer(p);assert.equal(model.assess(p,{...correct,sequence:[...correct.sequence].reverse()}).allCorrect,false);assert.equal(model.assess(p,correct).allCorrect,true);});
test('invalid DNS inputs fail explicitly',()=>{assert.throws(()=>model.validateProblem({records:[],query:{domain:'bad'}}),/records/);assert.throws(()=>model.validateProblem({records:[{domain:'x.example',ip:'999.1.1.1',serverId:'s'}],cache:{},query:{domain:'x.example'}}),/valid/);});
test('256 seeded scenarios reproduce, vary, cover hit miss and missing, and hide answers',()=>{const prints=new Set(),outcomes=new Set();for(let seed=1;seed<=256;seed++){const a=factory.create(lesson.expert,{seed}),b=factory.create(lesson.expert,{seed});assert.deepEqual(plain(a),plain(b));generator.validateScenario(a.data);prints.add(a.fingerprint);const r=model.resolve(a.data.problem);outcomes.add(r.found?r.cacheResult:'missing');assert.equal(/oracle|resolvedIp|destinationServerId|sequence/.test(JSON.stringify(a.data)),false);}assert.ok(prints.size>200);assert.deepEqual([...outcomes].sort(),['hit','miss','missing']);});
test('Expert and challenge require complete model output',()=>{const scenario=factory.create(lesson.expert,{seed:73}),correct=answer(scenario.data.problem);const partial=new Runner({definition:lesson.expert,scenario});assert.notEqual(partial.submitPrediction({cacheResult:correct.cacheResult}).status,'expert_perfect');const right=new Runner({definition:lesson.expert,scenario});assert.equal(right.submitPrediction(correct).status,'expert_perfect');const challenge=new Challenge({phases:[{goal:{type:'outcome_equals',expected_outcome:'solved'}}]});assert.notEqual(challenge.reportOperation({operation:'dns-attempt',state:{outcome:'attempted'}}).status,'challenge_completed');assert.equal(challenge.reportOperation({operation:'resolve-dns',state:{outcome:'solved'}}).status,'challenge_completed');});
test('lesson uses DNS generators and contains no scripted result state',()=>{const text=JSON.stringify(lesson.visualization);for(const key of ['guided_steps','next_state','target_state','oracle'])assert.equal(text.includes(key),false);assert.equal(lesson.expert.generator,'dns');for(const level of lesson.mastery.levels.slice(1))assert.equal(level.scenario.generator,'dns');});
