/* Run: node --test tests/http.test.cjs */
const { test }=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs'); const vm=require('node:vm'); const context=vm.createContext({console,window:{crypto:require('node:crypto').webcrypto}});
for(const file of ['scenario_factory.js','challenge_runner.js','expert_attempt_runner.js','engine/http_model.js','engine/http_generator.js'])vm.runInContext(fs.readFileSync(`static/js/${file}`,'utf8'),context,{filename:file});
const model=vm.runInContext('HttpModel',context),generator=vm.runInContext('HttpGenerator',context),factory=vm.runInContext('ScenarioFactory',context),Runner=vm.runInContext('ExpertAttemptRunner',context),Challenge=vm.runInContext('ChallengeRunner',context);const lesson=JSON.parse(fs.readFileSync('lessons/computer_networks/http-request-response.json','utf8'));const plain=v=>JSON.parse(JSON.stringify(v));
const responseFor=p=>{const req=p.goal.request,r=model.execute(p.server,req);return{...req,status:r.response.status};};
test('GET existing route returns model-generated 200',()=>{const p=lesson.visualization.problems[0],r=model.execute(p.server,p.goal.request);assert.equal(r.response.status,200);assert.equal(r.response.body,'About page');});
test('missing path returns 404 rather than authored success',()=>{const p=lesson.visualization.problems[1],r=model.execute(p.server,p.goal.request);assert.equal(r.response.status,404);assert.match(r.response.body,/No resource/);});
test('configured server failure returns 500',()=>{const p=lesson.visualization.problems[2],r=model.execute(p.server,p.goal.request);assert.equal(r.response.status,500);});
test('wrong method returns 405 and missing POST body returns 400',()=>{const s=lesson.visualization.problems[0].server;assert.equal(model.execute(s,{method:'POST',path:'/about'}).response.status,405);assert.equal(model.execute(s,{method:'POST',path:'/messages'}).response.status,400);});
test('valid POST body creates a resource',()=>{const s=lesson.visualization.problems[0].server,r=model.execute(s,{method:'POST',path:'/messages',body:'hello'});assert.equal(r.response.status,201);});
test('assessment grades method path and actual consequence independently',()=>{const p=lesson.visualization.problems[0];assert.equal(model.assess(p,{method:'GET',path:'/missing',status:404}).allCorrect,false);assert.equal(model.assess(p,responseFor(p)).allCorrect,true);});
test('invalid requests and servers fail explicitly',()=>{const s=lesson.visualization.problems[0].server;assert.throws(()=>model.execute(s,{method:'DELETE',path:'/'}),/supports GET and POST/);assert.throws(()=>model.execute(s,{method:'GET',path:'about'}),/begin with/);});
test('256 seeded scenarios reproduce, vary, cover HTTP outcomes, and hide responses',()=>{const prints=new Set(),statuses=new Set();for(let seed=1;seed<=256;seed++){const a=factory.create(lesson.expert,{seed}),b=factory.create(lesson.expert,{seed});assert.deepEqual(plain(a),plain(b));generator.validateScenario(a.data);prints.add(a.fingerprint);statuses.add(model.execute(a.data.problem.server,a.data.problem.goal.request).response.status);assert.equal(Object.hasOwn(a.data,'oracle')||Object.hasOwn(a.data,'response')||Object.hasOwn(a.data,'expectedResult'),false);}assert.ok(prints.size>200);assert.deepEqual([...statuses].sort(),[200,404,500]);});
test('Expert and challenge reject bypasses and require exact model prediction',()=>{const scenario=factory.create(lesson.expert,{seed:91}),correct=responseFor(scenario.data.problem);const wrong=new Runner({definition:lesson.expert,scenario});assert.notEqual(wrong.submitPrediction({...correct,status:200===correct.status?404:200}).status,'expert_perfect');const right=new Runner({definition:lesson.expert,scenario});assert.equal(right.submitPrediction(correct).status,'expert_perfect');const challenge=new Challenge({phases:[{goal:{type:'outcome_equals',expected_outcome:'solved'}}]});assert.notEqual(challenge.reportOperation({operation:'http-attempt',state:{outcome:'attempted'}}).status,'challenge_completed');assert.equal(challenge.reportOperation({operation:'send-request',state:{outcome:'solved'}}).status,'challenge_completed');});
test('lesson uses HTTP generators and contains no scripted response state',()=>{const text=JSON.stringify(lesson.visualization);for(const key of ['guided_steps','next_state','target_state','oracle'])assert.equal(text.includes(key),false);assert.equal(lesson.expert.generator,'http');for(const level of lesson.mastery.levels.slice(1))assert.equal(level.scenario.generator,'http');});
