/* Run: node --test tests/ip_addresses.test.cjs */
const { test } = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const vm = require('node:vm');
const context = vm.createContext({ console, window: { crypto: require('node:crypto').webcrypto } });
for (const file of ['scenario_factory.js','challenge_runner.js','expert_attempt_runner.js','engine/ipv4_address.js','engine/ip_generator.js']) vm.runInContext(fs.readFileSync(`static/js/${file}`,'utf8'), context, { filename:file });
const model=vm.runInContext('IPv4Address',context), generator=vm.runInContext('IpGenerator',context), factory=vm.runInContext('ScenarioFactory',context), Runner=vm.runInContext('ExpertAttemptRunner',context), Challenge=vm.runInContext('ChallengeRunner',context);
const lesson=JSON.parse(fs.readFileSync('lessons/computer_networks/ip-addresses.json','utf8')); const plain=v=>JSON.parse(JSON.stringify(v));
test('IPv4 parser enforces four numeric octets from 0 to 255',()=>{ assert.equal(model.isValid('192.168.1.20'),true); for(const value of ['1.2.3','1.2.3.256','a.2.3.4','1.2.3.-1']) assert.equal(model.isValid(value),false); });
test('normalization and construction preserve octet order',()=>{ assert.equal(model.normalize('192.168.001.020'),'192.168.1.20'); const p=lesson.visualization.problems[1]; assert.equal(model.execute(p).address,'192.168.1.20'); });
test('validation tasks derive validity instead of reading an answer',()=>{ const result=model.execute(lesson.visualization.problems[0]); assert.equal(result.valid,false); assert.match(result.explanation,/255/); });
test('endpoint tasks derive source and destination from packet data',()=>{ const result=model.execute(lesson.visualization.problems[2]); assert.equal(result.sourceAddress,'192.168.1.10'); assert.equal(result.destinationAddress,'192.168.1.20'); });
test('routing matches the complete destination address',()=>{ const result=model.execute(lesson.visualization.problems[3]); assert.equal(result.destinationDeviceId,'printer'); });
test('field assessment rejects wrong and partial responses',()=>{ const p=lesson.visualization.problems[2]; assert.equal(model.assess(p,{sourceAddress:'192.168.1.10'}).allCorrect,false); assert.equal(model.assess(p,{sourceAddress:'192.168.1.10',destinationAddress:'192.168.1.20'}).allCorrect,true); });
test('invalid problems fail explicitly',()=>{ assert.throws(()=>model.validateProblem({devices:[],task:{kind:'route-packet'}}),/needs devices/); assert.throws(()=>model.validateProblem({devices:[{id:'a',name:'A',address:'1.1.1.1'},{id:'b',name:'B',address:'1.1.1.1'}],task:{kind:'validate-address',candidate:'1.1.1.1'}}),/unique/); });
test('256 seeded scenarios reproduce, vary, cover every task, and hide answers',()=>{ const prints=new Set(), kinds=new Set(); for(let seed=1;seed<=256;seed++){ const a=factory.create(lesson.expert,{seed}), b=factory.create(lesson.expert,{seed}); assert.deepEqual(plain(a),plain(b)); generator.validateScenario(a.data); prints.add(a.fingerprint); kinds.add(a.data.problem.task.kind); assert.equal(/oracle|answer|result/.test(JSON.stringify(a.data)),false); } assert.ok(prints.size>200); assert.deepEqual([...kinds],['route-packet']); });
test('Expert and challenge accept only a model-correct endpoint',()=>{ const scenario=factory.create(lesson.expert,{seed:41}); const expected=model.execute(scenario.data.problem).destinationDeviceId; const wrong=new Runner({definition:lesson.expert,scenario}); assert.notEqual(wrong.submitPrediction({destinationDeviceId:'wrong'}).status,'expert_perfect'); const right=new Runner({definition:lesson.expert,scenario}); assert.equal(right.submitPrediction({destinationDeviceId:expected}).status,'expert_perfect'); const challenge=new Challenge({phases:[{goal:{type:'outcome_equals',expected_outcome:'solved'}}]}); assert.notEqual(challenge.reportOperation({operation:'ip-attempt',state:{outcome:'attempted'}}).status,'challenge_completed'); assert.equal(challenge.reportOperation({operation:'route-packet',state:{outcome:'solved'}}).status,'challenge_completed'); });
test('lesson uses executable generators and contains no scripted answer states',()=>{ const text=JSON.stringify(lesson.visualization); for(const key of ['guided_steps','next_state','target_state','oracle']) assert.equal(text.includes(key),false); assert.equal(lesson.expert.generator,'ipv4'); for(const level of lesson.mastery.levels.slice(1)) assert.equal(level.scenario.generator,'ipv4'); });
